import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const { isLoaded, isSignedIn, user } = useUser();
  const {data} = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-purple-600 to-purple-300">
        <h1>hello world!!</h1>
        <div>{!isSignedIn && <SignInButton />}</div>
        <div>{!!isSignedIn && <SignOutButton />}</div>
        <div>{data?.map((post) => <div key={post.id}>{post.content}</div> )}</div>
      </main>
    </>
  );
}
